# Numpy: Package for Multidimensional array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
simple_list

[6, 7, 9]

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [7]:
np.arange(1,30,5) # shift+tab->help box

array([ 1,  6, 11, 16, 21, 26])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((12,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones(108)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(15,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,5)

array([[0.44197269, 0.87271784, 0.19168913, 0.73943659, 0.45338222],
       [0.48448093, 0.98528636, 0.54651319, 0.76327327, 0.53907289],
       [0.37642805, 0.14410234, 0.97422115, 0.45079307, 0.30089847]])

In [21]:
arr=np.random.randn(2,4)
arr

array([[ 0.1789304 ,  0.27024085, -0.85542606, -1.17943698],
       [-1.0102722 ,  1.07639445, -0.84770073,  1.01793705]])

In [22]:
np.random.randint(2,100)

5

In [23]:
np.random.randint(20,56,100)

array([37, 52, 51, 39, 40, 25, 34, 36, 47, 22, 55, 54, 32, 27, 50, 49, 50,
       52, 26, 27, 45, 35, 25, 23, 49, 53, 37, 33, 20, 41, 52, 31, 25, 55,
       54, 30, 34, 25, 44, 21, 34, 48, 51, 48, 21, 30, 39, 44, 31, 25, 43,
       23, 28, 46, 55, 41, 21, 39, 50, 31, 20, 32, 52, 38, 48, 35, 20, 50,
       48, 46, 30, 35, 22, 22, 44, 20, 49, 46, 44, 45, 36, 22, 21, 39, 41,
       40, 36, 53, 55, 38, 53, 54, 38, 29, 37, 39, 23, 25, 39, 22])

In [24]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
rand_array=np.random.randint(0,100,20)
rand_array

array([ 7, 98, 32, 15, 95, 10, 85, 88, 64, 35, 64, 40, 58, 37, 60, 31, 87,
       72, 33, 66])

In [26]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [28]:
sample_array.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [29]:
rand_array.max()

98

In [30]:
rand_array.argmax()

1

In [31]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a=np.random.rand(2,3)
a

array([[0.55004487, 0.16251582, 0.57697438],
       [0.0120085 , 0.06557542, 0.40615306]])

In [34]:
a.T

array([[0.55004487, 0.0120085 ],
       [0.16251582, 0.06557542],
       [0.57697438, 0.40615306]])

In [35]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
sample_array[0]

10

In [37]:
sample_array[2:5]

array([12, 13, 14])

In [38]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional array

In [43]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [44]:
sample_matrix[1,2]

21

In [45]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [46]:
sample_matrix[2]

array([56, 76, 24,  7])

In [47]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# Selection techniques

In [48]:
sample_array=np.arange(1,20)

In [49]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [51]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [52]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [53]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [54]:
np.max(sample_array)

19

In [55]:
np.min(sample_array)

1

In [56]:
np.argmax(sample_array)

18

In [57]:
np.argmin(sample_array)

0

In [58]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [59]:
np.std(sample_array)

5.477225575051661

In [60]:
np.var(sample_array)

30.0

In [61]:
np.mean(sample_array)

10.0

In [62]:
array=np.random.randn(3,4)
array

array([[-1.56265757,  0.25489276,  0.18606893, -0.26170917],
       [ 0.2597287 , -1.32001724,  0.05537109,  0.16755384],
       [-1.08988229,  0.12124737, -1.21873838,  0.33338221]])

In [63]:
np.round(array,decimals=2)

array([[-1.56,  0.25,  0.19, -0.26],
       [ 0.26, -1.32,  0.06,  0.17],
       [-1.09,  0.12, -1.22,  0.33]])

In [64]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# creating one dimensional numpy array(Vector)

In [66]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [67]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [68]:
type(a)

numpy.ndarray

# creating two dimensional numpy array (Matrix)

In [69]:
b=np.array([1,2,3],[4,5,6])
b

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [70]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b=np.array([[1,2,3],[4,5,6,7,8]])
b

C:\Users\Admin\AppData\Local\Temp\ipykernel_14748\2510602567.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[4,5,6,7,8]])


array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

In [72]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [73]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [74]:
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [75]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [76]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1,10,3)

array([1, 4, 7])

In [78]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [83]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [84]:
np.random.rand(3,5)

array([[0.24589934, 0.30452175, 0.8299692 , 0.73452067, 0.91934693],
       [0.14838636, 0.79567833, 0.23371564, 0.28979322, 0.21803763],
       [0.90116261, 0.37764799, 0.19842309, 0.39245532, 0.16054794]])

In [85]:
np.random.randn(3,5)

array([[-2.22124292,  0.23545861,  2.15166716, -1.30225225,  0.9381759 ],
       [-0.02158256, -0.62796697,  0.73190158,  1.07913267,  0.59247416],
       [-0.52938774, -0.79785722,  0.14964652,  1.19783945,  0.64400287]])

In [86]:
np.random.randint(3,50)

37

In [87]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [88]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [89]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [91]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a2=np.arange(10,dtype=float)
a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [93]:
a2=a2.reshape(2,5)
a2

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [94]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
a4=np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
a4=np.arange(64).reshape(4,4,4)
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [97]:
a1.ndim

1

In [98]:
a2.ndim

2

In [99]:
a3.ndim

3

In [100]:
a4.ndim

3

In [101]:
a1.shape

(10,)

In [102]:
a2.shape

(2, 5)

In [103]:
a3.shape

(2, 2, 2)

In [104]:
a4.shape

(4, 4, 4)

In [105]:
a1.size

10

In [106]:
a2.size

10

In [107]:
a3.size

8

In [108]:
a4.size

64

# Changing data type

In [109]:
x=np.array([1.9,2.0,3.0])
x

array([1.9, 2. , 3. ])

In [110]:
x.astype(int)

array([1, 2, 3])

In [111]:
a=np.arange(12).reshape(3,4)

In [112]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [114]:
a*21

array([[  0,  21,  42,  63],
       [ 84, 105, 126, 147],
       [168, 189, 210, 231]])

In [115]:
a-5

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [116]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [117]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [118]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [119]:
a%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [120]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
b>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [122]:
b>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [123]:
a+b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [124]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [125]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [126]:
a/b

C:\Users\Admin\AppData\Local\Temp\ipykernel_14748\1348051284.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [127]:
a**b

array([[         1,          1,          4,         27],
       [       256,       3125,      46656,     823543],
       [  16777216,  387420489, 1410065408, 1843829075]], dtype=int32)

In [128]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
c=np.random.random((3,3))
c

array([[0.58753395, 0.24623829, 0.49254511],
       [0.28553981, 0.39521525, 0.37573425],
       [0.55029218, 0.26667043, 0.79452031]])

In [131]:
a=np.round(c*100)
a

array([[59., 25., 49.],
       [29., 40., 38.],
       [55., 27., 79.]])

In [132]:
np.max(a)

79.0

In [133]:
np.min(a)

25.0

In [134]:
np.sum(a)

401.0

In [135]:
np.prod(a)

373751746830000.0

In [136]:
np.max(a,axis=1)

array([59., 40., 79.])

In [137]:
np.min(a,axis=1)

array([25., 29., 27.])

In [138]:
np.max(a,axis=0)

array([59., 40., 79.])

In [139]:
np.prod(a,axis=0)

array([ 94105.,  27000., 147098.])

In [140]:
np.mean(a)

44.55555555555556

In [141]:
np.mean(a,axis=1)

array([44.33333333, 35.66666667, 53.66666667])

In [142]:
np.mean(a,axis=0)

array([47.66666667, 30.66666667, 55.33333333])

In [143]:
np.median(a,axis=1)

array([49., 38., 55.])

In [144]:
np.median(a,axis=0)

array([55., 27., 49.])

In [145]:
np.std(a,axis=1)

array([14.26728971,  4.78423336, 21.2498366 ])

In [146]:
np.var(a,axis=1)

array([203.55555556,  22.88888889, 451.55555556])

In [147]:
np.sin(a)

array([[ 0.63673801, -0.13235175, -0.95375265],
       [-0.66363388,  0.74511316,  0.29636858],
       [-0.99975517,  0.95637593, -0.44411267]])

In [148]:
np.cos(a)

array([[-0.77108022,  0.99120281,  0.30059254],
       [-0.74805753, -0.66693806,  0.95507364],
       [ 0.02212676, -0.29213881, -0.89597095]])

In [149]:
np.tan(a)

array([[ -0.82577401,  -0.13352641,  -3.17290855],
       [  0.88714284,  -1.11721493,   0.31030966],
       [-45.18308791,  -3.2737038 ,   0.49567753]])

In [152]:
np.cot(a)

AttributeError: module 'numpy' has no attribute 'cot'